- name: add sensu related apt keys
  apt_key: url="{{item}}"
  tags: install_sensu
  with_items:
    - "http://repositories.sensuapp.org/apt/pubkey.gpg"

- name: add sensu related repos
  apt_repository: repo="{{item}}" update_cache=yes
  tags: install_sensu
  with_items:
    - "deb  http://repositories.sensuapp.org/apt sensu main"

- name: install sensu related packages
  apt: name="{{item}}"
  tags:
    - install_sensu
  with_items:
    - "sensu"

- name: enable sensu client service.
  service: name=sensu-client enabled=yes

- name: add sensu permission to run cl-bgp
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^sensu"
    line: "sensu ALL = NOPASSWD: /usr/bin/cl-bgp"
    validate: 'visudo -cf %s'

- name: install sensu plugins
  tags:
    - copy_sensu_plugins
    - sensu_config
  copy: src=plugins  dest=/etc/sensu/ mode=755 directory_mode=0750 owner=sensu backup=yes

- name: make the sensu ssl directory
  tags:
    - sensu_ssl_config
    - sensu_config
  file: path=/etc/sensu/ssl state=directory

- name: copy cert.pem and key.pem for connection to rabbitmq - insecure
  tags:
    - sensu_config
    - sensu_ssl_config
  copy:  src=files/{{item}} dest=/etc/sensu/ssl/ owner=sensu mode=440
  with_items:
    - cert.pem
    - key.pem
  notify:
      - restart sensu client

- name: rabbitmq and client.json configs
  tags:
    - sensu_config
    - sensu_client_config
  template: src="{{item}}.json.j2" dest="/etc/sensu/conf.d/{{item}}.json"
  with_items:
    - client
    - rabbitmq
  notify:
    - restart sensu client

    #- name: add rsyslog imfile to rsyslog.conf
    #  tags:
    #    - sensu_client_config
    #    - rsyslog_config
    #  lineinfile:
    #    dest: "/etc/rsyslog.conf"
    #    regexp: "^\\$ModLoad imfile"
    #    insertafter: "^\\$ModLoad imklog"
    #    line: "\\$ModLoad imfile"
    #  notify:
    #    - restart rsyslog
    #
- name: add rsyslog sensu file
  template: src=35-sensu.conf.j2 dest=/etc/rsyslog.d/35-sensu.conf
  notify:
     - restart rsyslog

- name: install netshow (remove later)
  apt: name="netshow"
